apiVersion: v1
kind: Service
metadata:
  name: kafka-db-forwarder-service
  namespace: factory
spec:
  selector:
    app: kafka-db-forwarder-deployment
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080